DEVICE_PATH := device/sts/a03br
VENDOR_PATH := vendor/sts/a03br
BOARD_VENDOR := sts
BOARD_DEVICE := a03br
TARGET_DEVICE := a03br
TARGET_SOC := pxa1928
TARGET_BOARD_PLATFORM := mrvl
BOARD_USES_MRVL_HARDWARE := true

# gpuが無理だったら
# TARGET_FORCE_CPU_UPLOAD := true


USE_DEVICE_SPECIFIC_CAMERA := true
TARGET_HAS_LEGACY_CAMERA_HAL1 := true
USE_CAMERA_STUB := false

# Audio
TARGET_USES_AOSP_AUDIO_POLICY := true
BOARD_USES_ALSA_AUDIO := true
BOARD_USES_GENERIC_AUDIO := false
USE_XML_AUDIO_POLICY_CONF := false
BOARD_USES_TINYALSA_AUDIO := true
BOARD_HAVE_LEGACY_AUDIO := true
BOARD_SUPPORTS_SOUND_TRIGGER := false
BOARD_SUPPORTS_SOUND_TRIGGER_HAL := false
AUDIO_FEATURE_ENABLED_OFFLOAD := false
AUDIO_FEATURE_ENABLED_PCM_OFFLOAD := false
AUDIO_FEATURE_ENABLED_FLAC_OFFLOAD := false
BOARD_USES_USB_AUDIO := false
BOARD_SUPPORTS_COMPRESS_OFFLOAD := false
TARGET_ENABLE_QC_AV_ENHANCEMENTS := false
TARGET_DISABLE_DASH := true
ENABLE_VENDOR_IMAGE := false

# build option
BOARD_NO_RECOVERY_PATCH := true
#　BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
# ALLOW_MISSING_DEPENDENCIES := true
BOARD_SUPPRESS_SECURE_ERASE := true
DISABLE_ASHMEM_TRACKING := true
BOARD_NO_SECURE_DISCARD := true
TARGET_NO_SENSOR_PERMISSION_CHECK := true
# TARGET_FS_CONFIG_GEN := $(DEVICE_PATH)/config.fs

#disable
BOARD_HAS_RADIO := false
BOARD_GPS_LIBRARIES := false
BOARD_PROVIDES_LIBRIL := false
BOARD_PROVIDES_RILD := false
BOARD_HAS_GPS := false
BOARD_HAS_NFC := false
BOARD_HAS_RADIO := false
BOARD_HAS_HDMI := false
BOARD_SUPPORTS_SOUND_TRIGGER := false
BOARD_SUPPORTS_SOUND_TRIGGER_HAL := false
WITHOUT_CHECK_API := true
MALLOC_SVELTE := true
TARGET_LOW_RAM_DEVICE := true

BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/sts/a03br/bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_MRVL := true

BOARD_WLAN_VENDOR := MRVL
WIFI_DRIVER_MODULE_PATH := "/lib/modules/sd8801.ko"
WIFI_DRIVER_MODULE_NAME	:= "sd8801"
WIFI_DRIVER_MODULE_ARG := "firmware_path=/system/etc/firmware/mrvl/sd8801_uapsta.bin cfg80211_wext=12 sta_name=wlan uap_name=wlan wfd_name=p2p fw_name=mrvl/sd8801_uapsta.bin"
WIFI_DRIVER_FW_PATH_PARAM := "/sys/module/sd8801/parameters/firmware_path"
WIFI_DRIVER_FW_PATH_STA := "/system/etc/firmware/mrvl/sd8801_uapsta.bin"
WIFI_DRIVER_FW_PATH_AP := "/system/etc/firmware/mrvl/sd8801_uapsta.bin"
WIFI_DRIVER_FW_PATH_P2P := "/system/etc/firmware/mrvl/sd8801_uapsta.bin"
WIFI_SDIO_IF_DRIVER_MODULE_PATH := "/lib/modules/mlan8801.ko"
WIFI_SDIO_IF_DRIVER_MODULE_NAME := "mlan8801"
WIFI_SDIO_IF_DRIVER_MODULE_ARG := ""
MRVL_WIRELESS_DAEMON_API := true

# key
TARGET_PROVIDES_KEYMASTER := false
BOARD_USE_SOFT_GATEKEEPER := true

# dex2oat
WITH_DEXPREOPT := true
WITH_DEXPREOPT_PIC := true
USE_DEX2OAT_DEBUG := false

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
TARGET_CPU_SMP := true

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic

TARGET_IS_64_BIT := true
TARGET_BUILD_64BIT := true
TARGET_SUPPORTS_64_BIT_APPS := true
TARGET_CPU_ABI_LIST_64_BIT := $(TARGET_CPU_ABI)
TARGET_CPU_ABI_LIST_32_BIT := $(TARGET_2ND_CPU_ABI),$(TARGET_2ND_CPU_ABI2)
TARGET_CPU_ABI_LIST := $(TARGET_CPU_ABI_LIST_64_BIT),$(TARGET_CPU_ABI_LIST_32_BIT)
ARCH_ARM_HAVE_TLS_REGISTER := true
TARGET_CPU_MEMCPY_OPT_DISABLE := true

#oat
DEX2OAT_TARGET_ARCH := arm64
DEX2OAT_TARGET_CPU_VARIANT := generic
DEX2OAT_TARGET_CPU_VARIANT_RUNTIME := default
DEX2OAT_TARGET_INSTRUCTION_SET_FEATURES := default

#ota
AB_OTA_UPDATER := false

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := TAB-A03-BR
TARGET_NO_FACTORYIMAGE :=true
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true

# Display
DEVICE_RESOLUTION := 1280x800
LANDSCAPE_RESOLUTION := 1280x800
PORTRAIT_RESOLUTION := 800x1280

# Graphics
USE_OPENGL_RENDERER := true
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3
ENABLE_WEBGL := true
BOARD_EGL_CFG := $(DEVICE_PATH)/prebuilt/egl.cfg
TARGET_USES_ION := true
BACKLIGHT_PATH := /sys/devices/platform/panel_vx5b1d.19/backlight/lcd-bl/brightness
BOARD_USE_BGRA_8888 := true
BOARD_EGL_NEEDS_HANDLE_VALUE := true
BOARD_ENABLE_OVERLAY := false
BOARD_HAVE_PIXEL_FORMAT_INFO := true


#prop
TARGET_SYSTEM_PROP := $(DEVICE_PATH)/system.prop

# File systems
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_FLASH_BLOCK_SIZE := 131072
## BOARD_RECOVERYIMAGE_PARTITION_SIZE := 10485760

BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1988100096
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USES_MALLOC_IMPL := jemalloc
BOARD_VOLD_EMMC_SHARES_DEV_MAJOR := true
TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/class/android_usb/f_mass_storage/lun%d/file"
BOARD_UMS_LUNFILE := "/sys/class/android_usb/f_mass_storage/lun0/file"
BOARD_USES_MMCUTILS := true
BOARD_HAS_NO_MISC_PARTITION := true
TARGET_USES_MKE2FS := true

# Kernel
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_CMDLINE := androidboot.selinux=permissive
BOARD_KERNEL_PAGESIZE := 2048
BOARD_RAMDISK_OFFSET := 0x01000000
BOARD_KERNEL_TAGS_OFFSET := 0x00000100
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_SECOND_OFFSET := 0x00f00000
BOARD_MKBOOTIMG_ARGS := \
    --base $(BOARD_KERNEL_BASE) \
    --pagesize $(BOARD_KERNEL_PAGESIZE) \
    --kernel_offset $(BOARD_KERNEL_OFFSET) \
    --ramdisk_offset $(BOARD_RAMDISK_OFFSET) \
    --tags_offset $(BOARD_KERNEL_TAGS_OFFSET) \
    --second_offset $(BOARD_SECOND_OFFSET) \
    --cmdline "$(BOARD_KERNEL_CMDLINE)"

BOARD_KERNEL_IMAGE_NAME := Image.gz-dtb
TARGET_IGNORES_KERNEL_HEADERS := true
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64

# Kernel - prebuilt
TARGET_FORCE_PREBUILT_KERNEL := true
ifeq ($(TARGET_FORCE_PREBUILT_KERNEL),true)
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
PRODUCT_COPY_FILES += \
    $(DEVICE_PATH)/prebuilt/kernel:kernel
endif

# Recovery
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
RECOVERY_SDCARD_ON_DATA := true
LZMA_RAMDISK_TARGETS := recovery
BOARD_RECOVERY_SWIPE := true
BOARD_SUPPRESS_EMMC_WIPE := true
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery/root/etc/recovery.fstab
TARGET_RECOVERY_DEVICE_DIRS += $(DEVICE_PATH)

include vendor/sts/a03br/BoardConfigVendor.mk

# SELinux
BOARD_SEPOLICY_DIRS := \
	$(DEVICE_PATH)/sepolicy

BOARD_SEPOLICY_UNION += \
    genfs_contexts \
    file_contexts
    
BOARD_SECCOMP_POLICY += $(DEVICE_PATH)/seccomp_policy
TARGET_SELINUX_ENFORCE := false
SELINUX_IGNORE_NEVERALLOWS := true
