DEVICE_PATH := device/sts/a03br
VENDOR_PATH := vendor/sts/a03br
BOARD_VENDOR := sts
BOARD_DEVICE := a03br
TARGET_DEVICE := a03br
TARGET_SOC := pxa1928
TARGET_BOARD_PLATFORM := pxa1928

# build option
BUILD_BROKEN_DUP_RULES := true
BOARD_NO_RECOVERY_PATCH := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
ALLOW_MISSING_DEPENDENCIES := true
BOARD_SUPPRESS_SECURE_ERASE := true
DISABLE_ASHMEM_TRACKING := true
BOARD_NO_SECURE_DISCARD := true
TARGET_NO_SENSOR_PERMISSION_CHECK := true
TARGET_REQUIRES_SYNCHRONOUS_SETSURFACE := true

# TARGET_FS_CONFIG_GEN := $(DEVICE_PATH)/config.fs

#disable
BOARD_GPS_LIBRARIES := false
BOARD_PROVIDES_LIBRIL := false
BOARD_PROVIDES_RILD := false
BOARD_HAS_GPS := false
BOARD_HAS_NFC := false
BOARD_HAS_RADIO := false
BOARD_HAS_HDMI := false
BOARD_SUPPORTS_SOUND_TRIGGER := false
WITHOUT_CHECK_API := true
MALLOC_SVELTE := true

# key
TARGET_PROVIDES_KEYMASTER := false
BOARD_USE_SOFT_GATEKEEPER := true

# dex2oat
WITH_DEXPREOPT := true
WITH_DEXPREOPT_PIC := true
PRODUCT_DEX_PREOPT_BOOT_FLAGS := --compiler-filter=speed-profile
PRODUCT_DEX_PREOPT_DEFAULT_FLAGS := --compiler-filter=speed
USE_DEX2OAT_DEBUG := false

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := cortex-a53
TARGET_CPU_SMP := true
TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a53
TARGET_IS_64_BIT := true
TARGET_BUILD_64BIT := true
TARGET_SUPPORTS_64_BIT_APPS := true
TARGET_USES_64_BIT_BINDER := true
TARGET_CPU_ABI_LIST_64_BIT := $(TARGET_CPU_ABI)
TARGET_CPU_ABI_LIST_32_BIT := $(TARGET_2ND_CPU_ABI),$(TARGET_2ND_CPU_ABI2)
TARGET_CPU_ABI_LIST := $(TARGET_CPU_ABI_LIST_64_BIT),$(TARGET_CPU_ABI_LIST_32_BIT)
TARGET_CPU_CORTEX_A53 := true
ARCH_ARM_HAVE_TLS_REGISTER := true
TARGET_CPU_MEMCPY_OPT_DISABLE := true

#oat
DEX2OAT_TARGET_ARCH := arm64
DEX2OAT_TARGET_CPU_VARIANT := cortex-a53
DEX2OAT_TARGET_CPU_VARIANT_RUNTIME := default
DEX2OAT_TARGET_INSTRUCTION_SET_FEATURES := default


#ota
AB_OTA_UPDATER := false

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := a03br
TARGET_NO_FACTORYIMAGE :=true
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true

# Display
DEVICE_RESOLUTION := 1280x800
LANDSCAPE_RESOLUTION := 1280x800
PORTRAIT_RESOLUTION := 800x1280

# Graphics
USE_OPENGL_RENDERER := true
TARGET_FORCE_HWC_FOR_VIRTUAL_DISPLAYS := true
EXTENDED_FONT_FOOTPRINT := true

# audio
USE_XML_AUDIO_POLICY_CONF := 1

#prop
TARGET_SYSTEM_PROP := $(DEVICE_PATH)/system.prop

# File systems
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1988100096
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USES_MKE2FS := true

# Kernel
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_CMDLINE := androidboot.selinux=permissive
BOARD_KERNEL_PAGESIZE := 2048
BOARD_RAMDISK_OFFSET := 0x01000000
BOARD_KERNEL_TAGS_OFFSET := 0x00000100
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_SECOND_OFFSET := 0x00f00000
BOARD_MKBOOTIMG_ARGS := \
    --base $(BOARD_KERNEL_BASE) \
    --pagesize $(BOARD_KERNEL_PAGESIZE) \
    --kernel_offset $(BOARD_KERNEL_OFFSET) \
    --ramdisk_offset $(BOARD_RAMDISK_OFFSET) \
    --tags_offset $(BOARD_KERNEL_TAGS_OFFSET) \
    --second_offset $(BOARD_SECOND_OFFSET) \
    --cmdline "$(BOARD_KERNEL_CMDLINE)"

BOARD_KERNEL_IMAGE_NAME := Image.gz-dtb
TARGET_IGNORES_KERNEL_HEADERS := true
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64

# Kernel - prebuilt
TARGET_FORCE_PREBUILT_KERNEL := true
ifeq ($(TARGET_FORCE_PREBUILT_KERNEL),true)
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
PRODUCT_COPY_FILES += \
    $(DEVICE_PATH)/prebuilt/kernel:kernel
endif

# Vendor partition configure
BOARD_USES_VENDORIMAGE := false

# Recovery
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
RECOVERY_SDCARD_ON_DATA := true
LZMA_RAMDISK_TARGETS := recovery
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery/root/fstab.pxa1928
TARGET_RECOVERY_DEVICE_DIRS += $(DEVICE_PATH)

# Security patch level
VENDOR_SECURITY_PATCH := 2021-08-01

include vendor/sts/a03br/BoardConfigVendor.mk

# SELinux
#BOARD_SEPOLICY_DIRS := \
	#$(DEVICE_PATH)/sepolicy/
BOARD_SECCOMP_POLICY += $(DEVICE_PATH)/seccomp_policy
SELINUX_IGNORE_NEVERALLOWS := true
