#ifndef _BDROID_BUILDCFG_H
#define _BDROID_BUILDCFG_H
#define BLE_VND_INCLUDED FALSE
#define BTA_HF_CLIENT_INCLUDED FALSE
#define BTA_AG_INCLUDED          FALSE
#define BTA_MAP_INCLUDED         FALSE
#define BTA_AV_SINK_INCLUDED     FALSE
#define BTA_AVRC_CONTROLLER_INCLUDED FALSE
#define BTA_PAN_INCLUDED         FALSE
#define BTA_DM_COD {0x1C, 0x05, 0x02}

#endif
