#ifndef _BDROID_BUILDCFG_H
#define _BDROID_BUILDCFG_H
#define BTM_DEF_LOCAL_NAME "PXA1928"
#define MAX_ACL_CONNECTIONS 4
#define MAX_L2CAP_CHANNELS 8
#define BLE_VND_INCLUDED FALSE
#define BTM_WBS_INCLUDED FALSE
#define BTIF_HF_WBS_PREFERRED FALSE
#endif
